# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'safespace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for safespace

pod 'MessageKit'

pod 'MessageInputBar'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'


  target 'safespaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'safespaceUITests' do
    # Pods for testing
  end

end
